version: '3.8'

services:
  web:
    image: node:14
    container_name: note_management_web
    working_dir: /app
    volumes:
      - ./frontend:/app
    ports:
      - "3333:3000"
    depends_on:
      - api
    networks:
      - note_management_network

  api:
    image: python:3.12-slim
    container_name: note_management_api
    working_dir: /app
    volumes:
      - ./backend:/app
    ports:
      - "8888:8000"
    environment:
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
      - MONGODB_URL=mongodb://${MONGO_USER}:${MONGO_PASSWORD}@${MONGO_HOST}:${MONGO_PORT}/${MONGO_DB}
    depends_on:
      - postgres
      - mongo
    networks:
      - note_management_network
    tty: true

  postgres:
    image: postgres:13
    container_name: note_management_postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./data_sql:/docker-entrypoint-initdb.d
    networks:
      - note_management_network

  mongo:
    image: mongo:5
    container_name: note_management_mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    ports:
      - "${MONGO_PORT}:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - note_management_network

networks:
  note_management_network:

volumes:
  postgres_data:
  mongo_data: